name: Coverage
on: push
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.12'
        architecture: x64
    - run: pip install nox==2024.3.2
    - run: pip install poetry==2.1.1
    - run: pip install nox-poetry==1.2.0
    - run: nox --sessions tests coverage
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
