name: Ruff
on: push
permissions:
  contents: read
jobs:
  ruff:
    name: RuffJob
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v1
        with:
         python-version: ${{ matrix.python-version }}
         architecture: x64
      - run: pip install ruff==0.9.10
      - run: ruff format --diff src/ tests/ docs/ noxfile.py docs/conf.py
      - uses: astral-sh/ruff-action@v3
        with:
          args: "check --fix"
          src: >-
            src/
            tests/
            plots/
            noxfile.py
            docs/conf.py
