name: Ruff
on: push
permissions:
  contents: read
jobs:
  ruff:
    name: RuffJob
    runs-on: ubuntu-latest
    steps:
      - name: format
        uses: actions/checkout@v4
        uses: astral-sh/ruff-action@v3
        with:
          args: "format --check --diff"
          src: >-
            src/
            tests/
            plots/
            noxfile.py
            docs/conf.py

      - name: lint
        uses: actions/checkout@v4
        uses: astral-sh/ruff-action@v3
        with:
          args: "check --fix"
          src: >-
            src/
            tests/
            plots/
            noxfile.py
            docs/conf.py
